### ISSUE TITLE
RangeError: Maximum call stack size exceeded (on datadome v1.9.0)

### ISSUE THREAD

**Issue by pixtop** [glizzykingdreko/Datadome-Captcha-Deobfuscator#2]
Error comes from @babel/traverse at
```
function traverseNode(node, opts, scope, state, path, skipKeys, visitSelf) {
                     ^

RangeError: Maximum call stack size exceeded
```

You can test using the Datadome code at https://edge-functions-bot-protection-datadome.vercel.app/blocked

**Comment by glizzykingdreko** [comment]
Paid updates for new versions [mail me](mailto:glizzykingdreko@protonmail.com)
